{% set name = "tornado-proxy-handlers" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tornado_proxy_handlers-{{ version }}.tar.gz
  sha256: c67cce10a6e5d5215944f1ec82938c9f6f0a49ae3233cab50dc5c40f219147fd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tornado >=6.0.2

test:
  imports:
    - tornado_proxy_handlers

about:
  home: http://github.com/timkpaine/tornado-proxy-handlers
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Tornado proxy handlers for HTTP requests and web sockets'

  description: |
    Tornado proxy handlers for HTTP requests and web sockets
  dev_url: https://github.com/timkpaine/tornado-proxy-handlers

extra:
  recipe-maintainers:
    - timkpaine
